### ISSUE TITLE
Musica del tutorial riparte dopo aver attaccato la presa e aperto e chiuso il Menu

### ISSUE THREAD

**Issue by AndywinXp** [AndywinXp/cautious-octo-spork#1]
## Quale problema stai incontrando?
Descrivi brevemente il bug:
* Quale parte del gioco è affetta? _Audio_
* Cosa succede durante il bug? _Dopo aver attaccato la presa durante il tutorial, la musica si spegne. Se apro e chiudo il menù principale, la musica riparte._
* Cosa dovrebbe invece succedere? _La musica dovrebbe restare spenta dopo aver chiuso il menù principale_
* Riproducibile in modo consistente

## Come riprodurre
Per riprodurre il bug:
1. Aprire il gioco, e iniziare una nuova partita
2. Interagire (usa) con la presa della corrente
3. Aprire il menù di gioco con Esc
4. Chiudere il menù di gioco tornando alla partita

**Comment by EmanueleBaronti1** [comment]
risolto
