### ISSUE TITLE
Esposizione bottiglia 2 - Bottiglia a Ignazio per la prima volta. Eliminiamo opzioni dialogo

### ISSUE THREAD

**Issue by mightypiratersm** [AndywinXp/cautious-octo-spork#103]
Forse mi odierai per questa Ema dato che ci avevi lavorato molto, ma riflettendoci è meglio che le altre opzioni di dialogo non compaiano.

_**Quindi dopo la battuta**_
Ignazio – Era questo il piano? Esporla sul mio bancone? Proprio io che ho iniziato una crociata con questa bevanda da damerini? Giammai! 

_**Senza selezionare le altre opzioni di dialogo** Guybrush dice direttamente_

Ma è uno stratagemma per attirare clienti. Nella vostra situazione: meglio un cliente damerino che nessun cliente, no?

_... e prosegue. Altre opzioni di dialogo fanno confusione in effetti_

**Comment by EmanueleBaronti1** [comment]
meglio così
