### ISSUE TITLE
SVIZZERO ARRABBIATO - ANIMAZIONI MANCANTI 2

### ISSUE THREAD

**Issue by mightypiratersm** [AndywinXp/cautious-octo-spork#150]
Manca per lo Svizzero anche queste animazioni in cui è arrabbiato . Vanno usate soprattutto per il finale in cui manda al diavolo l'albero (oltre al girarsi c'è il lypsinc nella cartella), ma magari anche in qualche battuta di dialogo (se serve te le evidenzio io)

https://drive.google.com/drive/u/0/folders/1IIP-CkYleMApDuR9I47CP9i-02yTpshD

(mi sembra siano nelle cartelle Colore e Lypsinc arrabbiato)

**Comment by EmanueleBaronti1** [comment]
la cartella del lip sync arrabbiato è vuota
