### ISSUE TITLE
Ripristinare dialogo mancante Kate

### ISSUE THREAD

**Issue by mightypiratersm** [AndywinXp/cautious-octo-spork#53]
_Ripristinare questo dialogo una volta preso il volantino. Deve poi rimanere fino a quando Kate non si scioglie i capelli_

Guybrush 5.1 – 
Nel volantino hai i capelli sciolti, ma ora li tieni legati. I clienti non ti riconosceranno!

K – 
L'unico imbecille che non mi riconosce con questa acconciatura nuova è la guardia di Phatt Island. E va bene così.

G – 
Non sottovalutare gli imbecilli. Sono ovunque.

K – 
Oh già, anche davanti a me!

G- 
Ehi!  Potresti incontrare un cliente spaventosamente ricco ma spaventosamente stupido. O miope. In entrambi i casi non ti riconoscerebbe.

K – 
Oh, guardami! Tremo di paura! Vorrei proprio incontrare un cliente così stupido e così miope.

**Comment by EmanueleBaronti1** [comment]
questo dialogo è inserito quando dai il volantino a kate
