### ISSUE TITLE
Kate gigante

### ISSUE THREAD

**Issue by mightypiratersm** [AndywinXp/cautious-octo-spork#98]
Ci schiaccerà tutti se non la riduciamo!
![image](https://github.com/AndywinXp/cautious-octo-spork/assets/154276592/4b36421f-dd14-4927-8635-a6fa47bad09e)

**Comment by EmanueleBaronti1** [comment]
come ha fatto a venir fuori così grande?

**Comment by mightypiratersm** [comment]
Non ti so dire, era così da inizio gioco appena sono entrato. Sono andato lì subito dopo il dialogo iniziale con Formaggio
